### ISSUE TITLE
student manual and mentor manual buttons are not responding correctly

### ISSUE THREAD

**Issue by tejaswini22199** [kossiitkgp/kwoc-bugs#1]
## Description of the Issue

* Link:
* URL:https://kossiitkgp.org/events/index.html
* Date Observed:26-11-20
![xyz](https://user-images.githubusercontent.com/43006347/100382646-cc170400-3041-11eb-92ef-6161253c5a76.JPG)
![xyz1](https://user-images.githubusercontent.com/43006347/100382650-cd483100-3041-11eb-9fb5-cbff1cfae29a.JPG)

**Comment by grapheo12** [comment]
Hey @tejaswini22199 , thanks for raising the issue. We have resolved the problem. Hence closing. :clinking_glasses:
