### ISSUE TITLE
Student Dashboard is Not Loading

### ISSUE THREAD

**Issue by Siddhant-K-code** [kossiitkgp/kwoc-bugs#11]
## Description of the Issue

`Student Dashboard` is showing `Server Error`
* URL: https://kwoc.kossiitkgp.org/dashboard/student

![image](https://user-images.githubusercontent.com/55068936/101297577-b1b60500-384f-11eb-878a-accfe0d417b9.png)

* Date Observed: 7 December 2020 | 05:30 AM IST

**Comment by NiharikaVadlamudi** [comment]
I've been facing the same error from past 2 days , despite proper Student registration. Pls propose an alternative if at all anything can be done from the user's side . (Tried different browsers --still doesn't work)

**Comment by Siddhant-K-code** [comment]
@NiharikaVadlamudi Till Then, if want to know about your stats, you can go to Stats -> Student Stats -> { your username } in table

**Comment by Nishant2907** [comment]
Same here, i have been facing this error since today morning.

**Comment by rakaar** [comment]
@Nishant2907 @Siddhant-K-code @NiharikaVadlamudi
sorry for the inconvenience
we have updated the stats just recently
Can you please check the dashboard and individual stats page now?

**Comment by Siddhant-K-code** [comment]
Yes, Now they are working smoothly, Great!
