### ISSUE TITLE
Wrong Index

### ISSUE THREAD

**Issue by codewithvk** [kossiitkgp/kwoc-bugs#12]
## Description of the Issue

In states of student PR shows (Merge/open) But it actually rates of (Open /Merge).

* URL: https://kwoc.kossiitkgp.org/stats/students
* Date Observed:

**Comment by codewithvk** [comment]
![Capture](https://user-images.githubusercontent.com/61119120/101346544-b4941280-38ae-11eb-804f-9a7370663076.PNG)
![Capture2](https://user-images.githubusercontent.com/61119120/101346592-ca093c80-38ae-11eb-93a0-89e58ddd1890.PNG)

**Comment by rakaar** [comment]
@codewithvk 
thanks for pointing the issue
we have fixed it
hence closing the issue :)
