### ISSUE TITLE
Error on my Student Dashboard

### ISSUE THREAD

**Issue by Kerveyfelix** [kossiitkgp/kwoc-bugs#16]
## Description of the Issue

2 of my pull open requests,commits and lines of code are not being shown on my dashboard. I have made commit and open pull request in [CGPA_Estimator Project](https://github.com/Codextream/CGPA_ESTIMATOR/pulls). However my dashboard is not taking this into an account.

* URL:
https://kwoc.kossiitkgp.org/dashboard/student

* Date Observed:
8/12/20

**Comment by rakaar** [comment]
hello @Kerveyfelix 
we have fixed it. The same stats can be found on the [individual stats page](https://kwoc.kossiitkgp.org/stats/student/kerveyfelix).
Closing the issue for now 
if u still find any issues, you can reopen the issue and mention the troubles :)
