### ISSUE TITLE
Mentor Projects submit button not working

### ISSUE THREAD

**Issue by Nishant2907** [kossiitkgp/kwoc-bugs#17]
## Description of the Issue
Mentor Projects submit button not working.

* URL:https://kwoc.kossiitkgp.org/form/project
* Date Observed: 08-12-2020

**Comment by mukul-mehta** [comment]
Do you have a screenshot or more details about the incident? Things seem to be working fine for other projects AFAIK. We could see if it's failing for your data

**Comment by Nishant2907** [comment]
I don't know but now its showing that this year mentor project registrations are closed. That's not fare, earlier i wasn't ablle to add a project and now its over...

**Comment by mukul-mehta** [comment]
Sorry for that. Could you please give your project's details, I'll see what I can do. Please specify name, a description, link to the repo, tags for the project, github link and communication channel link

**Comment by Nishant2907** [comment]
Project Name:  Hashcode
Project Details: This project is build to make coding knowledge available to every place through an app and a website. This is an online platform to learn different languages from the best hand-picked courses.
Link: https://github.com/inaxia/hashcode_web
Tags: Html, css, Javascript, Web Development
My Github profile: https://github.com/Nishant2907
Gitter channel: https://gitter.im/inaxia-group/hashcode-web?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Hardikkr** [comment]
I also want to add my project in KWOC... 
My project details are provided below:

Project Details: This project is build to make coding knowledge available to every place through an app and a website. This is an online platform to learn different languages from the best hand-picked courses.
Link: https://github.com/inaxia/hashcode_app
Tags: Flutter, Dart
My Github profile: https://github.com/Hardikkr
Gitter channel: https://gitter.im/inaxia-group/hascode-app?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by sahil-shubham** [comment]
@Nishant2907 and @Hardikkr we have added your projects into our database. You can check the same on the projects page on KWoC's website (https://kwoc.kossiitkgp.org/projects). 

Let us know if we need to change anything, this issue can be closed now.
