### ISSUE TITLE
Registration after the Timeline

### ISSUE THREAD

**Issue by gaurang8989** [kossiitkgp/kwoc-bugs#18]
## Description of the Issue

I registered as a Student in https://kwoc.kossiitkgp.org/ Site on 08-December-2020 after the 06-December-2020 threw Github Authorization.
**Screen Shot of Student dashbord at below**
**My GitHub Handle : https://github.com/gaurang8989**
* URL: https://kwoc.kossiitkgp.org/
https://github.com/gaurang8989
* Date Observed: 08-December-2020
![Screenshot (1395)](https://user-images.githubusercontent.com/54485172/101512750-5c8a0880-39a1-11eb-8efc-cda907c89e7f.png)

**Comment by mukul-mehta** [comment]
We received a couple of mails for extending registration and hence did it. We couldn't update the timeline, sorry for that. Registrations have closed again now. Thank You for reporting this issue
