### ISSUE TITLE
Mobile view not correct

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/kwoc-bugs#2]
The page has a bad mobile veiw.
![Screenshot_20201127-101539_Chrome](https://user-images.githubusercontent.com/68731551/100412074-8b4ad980-3099-11eb-8068-53dbd3eadfb0.jpg)

**Comment by yashrsharma44** [comment]
Thanks for reporting this, we are aware of this issue, and we will soon fix it.

**Comment by djbarnwal** [comment]
@rakaar Can this be closed now?
