### ISSUE TITLE
are spamming pull requests like editing readme files allowed?

### ISSUE THREAD

**Issue by khushi0704** [kossiitkgp/kwoc-bugs#20]
I saw the stats page in the kwoc , and saw the current top student named Ayush Kumar's stats (ayush7614) and 90% of the contribution he made was of updating , creating , deleting readme files , you can yourself check it.
I don't know if that is allowed because I think that breaks the integrity of a competition just like what hapenned in HACKTOBER fest.
![Screenshot (67)](https://user-images.githubusercontent.com/64957861/101904918-9e52c300-3bdc-11eb-8ade-d38ac75c0ffd.png)

**Comment by rakaar** [comment]
@khushi0704 
The repository is a knowledge base repository, where contributions are made in readme files only. You can look at the files changed, by clicking on each commit.
 Also as the mentor of the project, is merging the pull requests, they can't be categorized as spam.

Also, the dashboard is for sake of encouraging the students, but not to create a competitive atmosphere!
