### ISSUE TITLE
stats scroll bug 

### ISSUE THREAD

**Issue by Harshith2255** [kossiitkgp/kwoc-bugs#21]
In the stats sections for students when we scroll down to the bottom of the list then you will notice that list acts very wierdly.

**Comment by rava-dosa** [comment]
Hi @Harshith2255 Apoorva here from KoSS. Can you please provide
1. Specifications of your computer
2. Provide some more details on what do you consider weird.
I just checked list, there is proper pagination and it works as it should.

**Comment by Harshith2255** [comment]
The list is blinking when we reach the bottom of the list and hover over the list

**Comment by rava-dosa** [comment]
Ok, so about that, blinking of list is an issue, we will have to add prerender and cache on scrolling logic, but I don't think that will be on priority yet given our current bandwidth, hence closing this issue.

**Comment by Harshith2255** [comment]
Not a problem i just wanted to help
 the society
