### ISSUE TITLE
Stats on dashboard incorrect

### ISSUE THREAD

**Issue by LazyCoder-1506** [kossiitkgp/kwoc-bugs#22]
## Description of the Issue

Actual stats : Commits- = 4, PRs = 3
Shown stats : Commits = 4, PRs = 2
Lines of code wrong (not a big issue)
Below in the table where commits are shown, most commits are shown twice (not a big issue)

![bug](https://user-images.githubusercontent.com/58332911/102013832-992a7b00-3d78-11eb-90e6-0af416786a45.png)

![bug2](https://user-images.githubusercontent.com/58332911/102013862-bf501b00-3d78-11eb-8cdc-c546797e3a8a.png)

**Comment by rava-dosa** [comment]
Hi Apoorva here from KoSS. I checked out your dashboard at this url https://kwoc.kossiitkgp.org/stats/student/LazyCoder-1506 . 
It is showing 4 pr's currently. I personally checked all the pr, each of them links to unique url. 
![Here is the view](https://i.imgur.com/lMdVaQy.png)
Can you please cross verify that even you are seeing the same view. There is some issue in the table showing commits, we are looking into it.

**Comment by rakaar** [comment]
Even in my machine, it shows the same number of PRs
regarding repeated commits, sorry for that. we will fix it
![image](https://user-images.githubusercontent.com/44907757/102078976-dbfc5980-3e31-11eb-9167-33c583a6e4a0.png)

**Comment by LazyCoder-1506** [comment]
in firefox and chrome incognito, PR is showing 4, but in normal chrome it is still having error

**Comment by rakaar** [comment]
> in firefox and chrome incognito, PR is showing 4, but in normal chrome it is still having error

seems an issue with caching from our side. we will try fixing it. sorry for the inconvenience.

**Comment by LazyCoder-1506** [comment]
> seems an issue with caching from our side. we will try fixing it. sorry for the inconvenience.
no problem.... as long as it is solved by the end all is well

**Comment by rakaar** [comment]
@LazyCoder-1506 
we have fixed the repeating commits issue.

can u send a screenshot of the pull requests that are being shown on ur stats(the one where fewer pull requests were present)

**Comment by LazyCoder-1506** [comment]
![image](https://user-images.githubusercontent.com/58332911/102121120-7330d380-3e69-11eb-9f9c-6e626fd55304.png)

![image](https://user-images.githubusercontent.com/58332911/102121149-7f1c9580-3e69-11eb-8ec6-466f28a69968.png)

**Comment by manishaag7** [comment]
I am also having the same issue. On the dashboard no of PR showing is 6 while i have done 11 PR.


![image](https://user-images.githubusercontent.com/55875847/102243092-cb76dc80-3f20-11eb-9080-b56c818e3b80.png)

![image](https://user-images.githubusercontent.com/55875847/102243257-f6613080-3f20-11eb-8009-7715951649d2.png)

**Comment by rava-dosa** [comment]
Hey great work for sending three pr's. We are having some caching issues I guess, If you want to visit your most recent data in our database please visit this url https://kwoc.kossiitkgp.org/stats/student/manishaag7

**Comment by rakaar** [comment]
@manishaag7 @LazyCoder-1506 
really sorry for that issue
we are trying to fix it
for temporarily, we have added a hard reload button at the **bottom of individual stats page and student dashboard**, you can click on it and it fetches all PRs ignoring the cache.
(the same effect can be achieved by opening on a different browser or incognito of the browser)
![image](https://user-images.githubusercontent.com/44907757/102258446-f3bc0680-3f33-11eb-9480-7fa921998577.png)

please, let us know if this is working or not? 
sorry again for the inconvenience caused

**Comment by LazyCoder-1506** [comment]
sorry to inform it's not working for me

**Comment by manishaag7** [comment]
This is working for me

**Comment by aashishat718** [comment]
@rakaar I am also facing these issues. My PR's are shown but number of commits and lines added and closed is always 0 (my PR's are already merged). Please look into the matter.
![image](https://user-images.githubusercontent.com/54476719/102404558-e5421d80-400d-11eb-9433-f402439a2d88.png)

**Comment by rakaar** [comment]
@aashishat718 the reason your commits are not being shown being Github is not considering it as a contribution from your account. By that I mean...
![image](https://user-images.githubusercontent.com/44907757/102411489-03ad1680-4018-11eb-94ef-2418ca281ca2.png)

In the above image you can see the commit in one of the repos you have contributed, beside your username, there is a github icon, instead there should be your display picture. This generally happens if your email configuration is incorrect. This is the first point mentioned in the Github Docs, you can check them [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#:~:text=Your%20local%20Git%20commit%20email,appear%20on%20your%20contributions%20graph.)


For your future commits to be counted as a contribution by Github, follow [these](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address) docs.

(The same issue has been faced by another student as well)
Don't worry regarding the mid evals, since we know you have made a legitimate commit, it will not be an issue.

**Comment by satyampandeygit** [comment]
when I registered my git username was TheWireGit now I have changed my name to satyampandeygit. Now when I am going to student dashboard initially it is showing "You have not registered in any project. Click OK to cancel this popup", when I click cancel for fraction of second it shows 9 PR which are the exact count then suddenly it changes to 0.

**Comment by LazyCoder-1506** [comment]
Others who have some kind of problems, please create your separate issues. The KWoC team is responding to everyone, but getting email notifications for something unnecessary is not very comfortable for me. please open your own issues

**Comment by rakaar** [comment]
Let this comment be the last comment of the issue. I have opened another issue regarding PRs(https://github.com/kossiitkgp/kwoc-bugs/issues/25). We can discuss that there. Before closing, I want to summarize the issues discussed and solutions for now

@LazyCoder-1506 
We have made few changes in the hard reload button can you please try again. And let us know in the comments of this issue - https://github.com/kossiitkgp/kwoc-bugs/issues/25

@satyampandeygit 
We have changed your username, it should be showing properly now. Sorry for the delay. If you are facing issue with PRs try the hard reload button at the bottom of the dashboard or bottom of the individual stats page. And let us know in the comments of this issue - https://github.com/kossiitkgp/kwoc-bugs/issues/25

@manishaag7 
Please let us know if there are still issues regarding the PRs even after hard reload  in this comments - https://github.com/kossiitkgp/kwoc-bugs/issues/25

@aashishat718 
I guess yours is a different issue and the solution to it has been discussed.
