### ISSUE TITLE
"Server Error, Please try again" in Mentor Dashboard

### ISSUE THREAD

**Issue by Hardikkr** [kossiitkgp/kwoc-bugs#23]
## Description of the Issue
Whenever I was trying to go to the Mentor Dashboard, I was getting a pop up saying `Server Error, Please try again`.
I tried to refresh many times but it never let me in to that page.

* URL: https://kwoc.kossiitkgp.org/dashboard/mentor
* Date Observed: 10/12/2020

## Screenshot
![image](https://user-images.githubusercontent.com/61787056/102065075-1a881900-3e1e-11eb-881c-2a17666179ea.png)

**Comment by Hardikkr** [comment]
I've added my project details in Issue #17 , do add that in KWOC.

**Comment by sahil-shubham** [comment]
@Hardikkr You were getting this alert because you weren't registered as a mentor in our database. We have added you and your respective project in our database. 

I am going to consider this issue as resolved now.

**Comment by Hardikkr** [comment]
Thank you @sahil-shubham
