### ISSUE TITLE
Redirect /dashboard

### ISSUE THREAD

**Issue by j-tesla** [kossiitkgp/kwoc-bugs#24]
## Description of the Issue
*Not a bug: (enhancement)*
It is better if `/dashboard` redirects to either `/dashboard/student` or `/dashboard/mentor` based on the current login.

* URL: https://kwoc.kossiitkgp.org/dashboard
* Date Observed: 18 Dec, 2020

**Comment by rakaar** [comment]
@j-tesla thing is in KWoC, one person can be both mentor and a student. 

On student dashboard, one can find the stats, resources
On mentor dashboard, one can find projects, and students worked, and different resources

If some person wants to have access to both the dashboards at the same time, the same URL for `/dashboard` won't work right? He has to log out of one to access the other, which is bad. Hence we have different URL for student and mentor dashboards.
