### ISSUE TITLE
PRs not being updated. Hard Reload button working?

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc-bugs#25]
## Description of the Issue

Some students are facing issue due to caching, on which we are still working. For that temporarily we have placed a Hard Reload button, which uses no cache. We have recently made changes in the hard reload button. Please mention below if the button works or fails. 

* URL: https://kwoc.kossiitkgp.org/dashboard/student, https://kwoc.kossiitkgp.org/stats/student/STUDENT_USERNAME
* Date Observed: 19 Dec

**UPDATE** -  I think the caching issue is fixed now. Please let us know if the pulls have been visible without using the hard reload button. Your feedback will help us to fix bugs if there are more related to the caching.

**Comment by LazyCoder-1506** [comment]
Many of my PRs are getting repeated. Total PRs (open + closed) should be 9, but on hard reloading using the button provided, it is showing 20 PRs. Commits are alright.

![image](https://user-images.githubusercontent.com/58332911/102688417-93231700-421c-11eb-8fea-5ab2ce55d257.png)

URL : [https://kwoc.kossiitkgp.org/stats/student/LazyCoder-1506](url)
Date observed : 19 Dec

**Comment by rakaar** [comment]
@LazyCoder-1506  
thanks for the quick update. We will try to fix it soon.

**Comment by LazyCoder-1506** [comment]
yes i checked now. stats are correct when the page reloads, as well as on clicking hard reload button. thank you

**Comment by yashasvimisra2798** [comment]
My number of commits reduced from 171 to 140. The number of lines of code reduced from 19k to 7k. Please check.

**Comment by rakaar** [comment]
@yashasvimisra2798  As the issue is regarding commits, I have opened a new issue - https://github.com/kossiitkgp/kwoc-bugs/issues/27 and also added a suggestion,
Let's discuss things over there. 

Sorry for the inconvenience.
