### ISSUE TITLE
Issued PR not taken into account

### ISSUE THREAD

**Issue by shobhit2020** [kossiitkgp/kwoc-bugs#26]
Good evening, 
I opened one PR, before time, i.e. 20th Dec 2020.
However the same PR without any issue got closed, somewhat late because my Mentor was some busy.
There's not a fault of the Mentor but the criteria for mid evaluation was atleast one PR, it can be opened or closed, I assume.
Please look into it.

**Comment by sahil-shubham** [comment]
Hi @shobhit2020, thank you for participating in KWoC. I would like to clarify that we judged participants based on their number of commits and not on how many PRs they made. This way we were able to limit the people who made pull requests which were not upto the mark according to the mentor. We count both the direct commits as well as the commits made after a PR is merged.

I hope it is clear why you didn't pass the evaluation. But, don't let this stop you from contributing to open source. Let us know if you still have any concerns, we can close this issue after your reply.

**Comment by shobhit2020** [comment]
Good afternoon,
Please read my issue once again.
I said that I've made a PR already whether it was opened or closed.
Also, my Mentor was somewhat late to merge my request, you can clarify,
please.

And please tell what are the number of commits, one should make to make up
the evaluation?

Thank you

**Comment by sahil-shubham** [comment]
> I said that I've made a PR already whether it was opened or closed.
Also, my Mentor was somewhat late to merge my request, you can clarify,

You mentioned in the first comment that the pull request was closed and not merged. It would be helpful if you could link the pull request we are talking about and I would take a look at it myself.

> Also, my Mentor was somewhat late to merge my request, you can clarify,

No need to worry about that, we will evaluate the pull request ourselves if needed. You just need 1 commit to pass the mid evaluation.

**Comment by shobhit2020** [comment]
Good evening, there

Here's the direct link for the PR I make/made, it just of one commit only.
My github name is shobhit2020.

https://github.com/Ayush7-BIT/Tinder_Website_for_dogs/pull/22

Please look into it and let me know if there's anything more I need to do.

Thank you

**Comment by sahil-shubham** [comment]
@shobhit2020 We have checked the linked PR and passed you in the mid evaluation. You can continue with contributing to your respective project. 

You would be able to see the changes in your dashboard in a few hours. Let us know if there is any other issue. I will close this issue after your reply.

**Comment by shobhit2020** [comment]
Thankyou
