### ISSUE TITLE
Commits not getting updated

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc-bugs#27]
## Description of the Issue

Number of commits reduced

* URL: /stats/STUDENT_USERNAME
* Date Observed: 26 Dec, 20

**Comment by rakaar** [comment]
![image](https://user-images.githubusercontent.com/44907757/103165215-d7c13a80-483a-11eb-949e-eba70ca2a54e.png)
@yashasvimisra2798 
Can u try clicking on the reload button beside `Pull Requests`  The spinner like thing, which can be seen on the right side of the above image.

**Comment by yashasvimisra2798** [comment]
@rakaar thank you! The issue is resolved now. I can see the correct number of commits and PR's.

**Comment by rakaar** [comment]
@yashasvimisra2798 
I think the issue for the small period of time was because stats were getting updated. Stats are updated for every hour. And for a few seconds each hour, the stats data is being overwritten. It might have happened that you might have checked your stats exactly during that short period of time. The same was faced by another student as well. In that case, we request you to check again after a minute or two. 
Closing this issue for now :)
Nevertheless, if you still face any issues, feel free to reopen this issue or report to us.
