### ISSUE TITLE
My account is not showing

### ISSUE THREAD

**Issue by KerinPithawala** [kossiitkgp/kwoc-bugs#28]
## Description of the Issue

My Github username was Kerveyfelix and I had passed mid-evaluations. However, after I changed my GitHub username to KerinPithawala today, and it's showing that I am not even registered on this program
![image](https://user-images.githubusercontent.com/46436993/103167580-30e89880-4852-11eb-956d-439cee4f9d08.png)
Kindly do the needful. 

* URL: https://kwoc.kossiitkgp.org/dashboard/student
* Date Observed:27/12/20

**Comment by rakaar** [comment]
We have changed your username in the DB. Thank you for notifying.
Closing this issue for now. If you feel there are any issues, feel free to re-open it :)
