### ISSUE TITLE
Add an option to edit the communication links

### ISSUE THREAD

**Issue by yashrsharma44** [kossiitkgp/kwoc-bugs#3]
Currently, some users might have added links to there communication channel incorrectly, so it becomes difficult for them to edit them. It would be nice if we could edit the communication links.

* URL: https://kwoc.kossiitkgp.org/dashboard/mentor
* Date Observed: 27th November, 2020

**Comment by rakaar** [comment]
Till this bug is fixed, mentors can mail the changes they wish to update in their project details.
