### ISSUE TITLE
Not received Certificate. 

### ISSUE THREAD

**Issue by codewithvk** [kossiitkgp/kwoc-bugs#30]
## Description of the Issue
I participate in KWOC as a student but I have not received a certificate. 

My state is https://kwoc20.kossiitkgp.org/stats/student/codewithvk 

and my GitHub username @codewithvk.

thanks in advance.

* URL: https://kwoc20.kossiitkgp.org/stats/student/codewithvk
My mail: codewithvk256@gmail.com

**Comment by codewithvk** [comment]
@yashrsharma44 sir can you help me?

**Comment by sahil-shubham** [comment]
@codewithvk Thank you for letting us know. We noticed that you had made a typo while giving us your email id. `codewithvk256@gmail.vom` - This is what we have in our database. We will change it to - `codewithvk256@gmail.com` and send you your certifcate in a few days.

**Comment by codewithvk** [comment]
@sahil-shubham  apologies for typo, Thanks for responding.
