### ISSUE TITLE
Project Queuing problem on projects page

### ISSUE THREAD

**Issue by ghulamyazdani** [kossiitkgp/kwoc-bugs#33]
## Description of the Issue

Whenever the mentor edits project details the projects that specific project get to the last of the queue.

* URL:https://kwoc.kossiitkgp.org/projects
* Date Observed: -01/12/2021

**Comment by sahil-shubham** [comment]
This has been fixed, projects are now sorted based on their description and tags size and number respectively. Thank you for reporting.
