### ISSUE TITLE
can not register as mentor with a github project owned by an org and not me

### ISSUE THREAD

**Issue by amitu** [kossiitkgp/kwoc-bugs#39]
## Description of the Issue

I am trying to register as a mentor, and am stuck at https://kwoc.kossiitkgp.org/form/project. In the github link field if I paste the URL: https://github.com/FifthTry/fpm, its not accepting it. The field gets cleared when it loses focus.

* URL: https://kwoc.kossiitkgp.org/form/project
* Date Observed: 8th Dec 2021

**Comment by rakaar** [comment]
Hey @amitu 
Can you once please try adding again as shown in the video - [https://watch.screencastify.com/v/Bv0cskBFQsu5Pm2aNgq9](https://watch.screencastify.com/v/Bv0cskBFQsu5Pm2aNgq9
)

If it still doesn't work, we will add the project manually in the DB on your behalf. You can edit the details of the project later from the Dashboard.

**Comment by amitu** [comment]
Cool it worked. I was not actually pasting the link and I was typing it.
