### ISSUE TITLE
Add an option to change student details

### ISSUE THREAD

**Issue by Xx-Ashutosh-xX** [kossiitkgp/kwoc-bugs#4]
## Description of the Issue

I can't edit my details, if I accidentally press submit.

* URL: https://kwoc.kossiitkgp.org/dashboard/student
* Date Observed: 30/11/20

**Comment by yashrsharma44** [comment]
Thanks for the feature-request, we will let you know about this.

**Comment by rakaar** [comment]
For now, you can write a mail to `admin@kossiitkgp.org` with the details that you wish to update.

**Comment by yashrsharma44** [comment]
Closing this, let me know if the solution doesn't work.
