### ISSUE TITLE
serious problem

### ISSUE THREAD

**Issue by Rishavgupta12345** [kossiitkgp/kwoc-bugs#41]
I have successfully completed 3 decent legitimate contribution and all my pull request has been merged but WHEN I AM OPENING MY STUDENT DASH BOARD ITS SHOWING THAT I DIDN'T QUALIFY THE MID EVALS  !!!!!! how this can be even possible

username :- Rishavgupta12345

**Comment by sahil-shubham** [comment]
You have already passed the midevals, I have checked our database. You can clear the local storage (ctrl+shift+r) and try to open the dashboard again.

**Comment by Rishavgupta12345** [comment]
thanks 🤗🤗
