### ISSUE TITLE
Project Page is not Opening.

### ISSUE THREAD

**Issue by saswatsamal** [kossiitkgp/kwoc-bugs#6]
## Description of the Issue
Today I registered for the KWOC and after registering I went to see the project page but I found that it is not opening. 

![image](https://user-images.githubusercontent.com/39031660/101053940-587b7680-35ae-11eb-81ee-51ecf3609e6d.png)
 
It is completely blank.

* URL: https://kwoc.kossiitkgp.org/project
* Date Observed: 03-12-2020

**Comment by Holmes7** [comment]
https://kwoc.kossiitkgp.org/projects

**Comment by saswatsamal** [comment]
Okay! So the link on the Student Dashboard page for Project page is: https://kwoc.kossiitkgp.org/project which needs to get changed.

![image](https://user-images.githubusercontent.com/39031660/101059476-53b9c100-35b4-11eb-9200-eb7e80507ad8.png)

**Comment by rakaar** [comment]
this has been fixed recently by @priyanshux, hence closing.
