### ISSUE TITLE
Project Name not visible

### ISSUE THREAD

**Issue by robustTechie** [kossiitkgp/kwoc-bugs#7]
## Description of the Issue
I added one project whose title is not visible neither on the website nor in the dashboard.
![SharedScreenshot](https://user-images.githubusercontent.com/52889867/101134038-c74ce400-362f-11eb-9add-057923acd7e8.jpg)

* URL: 
* Date Observed: 4 Dec 2020

**Comment by rakaar** [comment]
Please mail us at `admin@kossiitkgp.org` to update the project name and description

**Comment by robustTechie** [comment]
Ok thanks :)

**Comment by rakaar** [comment]
@robustTechie 
Since this issue has been fixed, we are closing it :)
