### ISSUE TITLE
About removing extra tags

### ISSUE THREAD

**Issue by sushamaborhade** [kossiitkgp/kwoc-bugs#8]
I want to remove  extra tags from project that are not necessary. It took lots of tags that is added by mistakes.

-  URL : https://kwoc.kossiitkgp.org/dashboard/mentor

-  Date Observed: 4/12/2020

**Comment by rakaar** [comment]
I guess the tags are updated, as we got the same request via mail. @sushamaborhade Can this issue be closed?
