### ISSUE TITLE
Join Channel Link for Project Lorax not working properly

### ISSUE THREAD

**Issue by armedjuror** [kossiitkgp/kwoc-bugs#9]
## Description of the Issue

In the projects page, Project Lorax is using a telegram channel to which the button should direct using URL. But On clicking the Join channel button, URL for the telegram group is loaded relatively or is loaded inside the kwoc web or simply it is concatenated with the kwoc web address. as (https://kwoc.kossiitkgp.org/t.me/loraxapp) instead of (t.me/loraxapp) in a _blank target.

* URL: https://kwoc.kossiitkgp.org/projects
* Date Observed: 06/12/2020

**Comment by rakaar** [comment]
@armedjuror 
we have fixed the issue. Thanks for pointing it out!
